[package]
name = "gears-ui"
version = "0.1.0"
edition = "2021"
authors = ["Anisse Astier <anisse@astier.eu>"]

[dependencies]
pixels = "0.12.1"
gilrs = "0.10.1"
cpal = "0.15.2"

[dependencies.winit]
version = "0.28.3"
default-features = false
features = ["wayland-dlopen", "wayland"]

[dependencies.gears]
path = "../"
