[package]
name = "gears-ui"
version = "0.1.0"
edition = "2021"
authors = ["Anisse Astier <anisse@astier.eu>"]

[dependencies]
pixels = "0.9.0"

[dependencies.winit]
version = "0.27.3"
default-features = false
features = ["wayland-dlopen", "wayland"]

[dependencies.gears]
path = "../"
