name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: sudo apt install -y libudev-dev libasound2-dev
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --workspace --verbose -- --skip test_roms
