[package]
name = "gears-desktop"
version = "0.1.0"
edition = "2021"
authors = ["Anisse Astier <anisse@astier.eu>"]

[dependencies]
log = { version = "0.4", features = ["std"] }
pollster = "0.3"

[dependencies.gears]
path = "../"

[dependencies.gears-ui-core]
path = "../ui-core"
